package com.knowledge.assistant.service;

import com.knowledge.assistant.entity.EmbeddingMetadata;
import com.knowledge.assistant.entity.UploadedFile;
import com.knowledge.assistant.repository.EmbeddingMetadataRepository;
import com.knowledge.assistant.repository.UploadedFileRepository;
import dev.langchain4j.data.document.Document;
import dev.langchain4j.data.document.splitter.DocumentSplitters;
import dev.langchain4j.data.embedding.Embedding;
import dev.langchain4j.data.segment.TextSegment;
import dev.langchain4j.model.embedding.onnx.bgesmallenq.BgeSmallEnQuantizedEmbeddingModel;
import dev.langchain4j.model.embedding.EmbeddingModel;
import dev.langchain4j.store.embedding.EmbeddingStore;
import dev.langchain4j.store.embedding.pinecone.PineconeEmbeddingStore;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class EmbeddingService {

    private final EmbeddingMetadataRepository metadataRepository;
    private final UploadedFileRepository fileRepository;
    private EmbeddingModel embeddingModel;
    private final EmbeddingStore<TextSegment> embeddingStore;

    public EmbeddingService(
            EmbeddingMetadataRepository metadataRepository,
            UploadedFileRepository fileRepository,
            @Value("${pinecone.api-key}") String pineconeApiKey,
            @Value("${pinecone.index}") String pineconeIndex,
            @Value("${pinecone.environment:gcp-starter}") String pineconeEnv,
            @Value("${pinecone.project-id:default}") String pineconeProjectId
    ) {
        this.metadataRepository = metadataRepository;
        this.fileRepository = fileRepository;
        
        this.embeddingStore = PineconeEmbeddingStore.builder()
                .apiKey(pineconeApiKey)
                .index(pineconeIndex)
                .environment(pineconeEnv)
                .projectId(pineconeProjectId)
                .build();
    }

    public void chunkAndEmbedDocument(Document document, UploadedFile uploadedFile) {
        System.out.println("Starting chunking and embedding for file: " + uploadedFile.getOriginalFileName());
        
        // Use storedFileName (UUID) for metadata to prevent 'ghost' data if IDs are reused
        document.metadata().add("fileUuid", uploadedFile.getStoredFileName());
        document.metadata().add("userId", uploadedFile.getUploadedBy().getId().toString());
        document.metadata().add("source", uploadedFile.getOriginalFileName());

        var documentSplitter = DocumentSplitters.recursive(500, 50);
        List<TextSegment> segments = documentSplitter.split(document);
        
        System.out.println("Chunks generated: " + segments.size());

        for (int i = 0; i < segments.size(); i++) {
            TextSegment segment = segments.get(i);
            dev.langchain4j.data.segment.TextSegment updatedSegment = TextSegment.from(
                segment.text(), 
                segment.metadata().copy().add("chunkIndex", String.valueOf(i))
            );

            Embedding embedding = getEmbeddingModel().embed(updatedSegment.text()).content();
            
            // Capture the ID generated by the store
            String vectorId = embeddingStore.add(embedding, updatedSegment);
            
            EmbeddingMetadata metadata = new EmbeddingMetadata();
            metadata.setVectorId(vectorId);
            metadata.setChunkText(updatedSegment.text());
            metadata.setUploadedFile(uploadedFile);
            metadataRepository.save(metadata);
        }
        
        System.out.println("Successfully embedded " + segments.size() + " segments into Pinecone.");
    }

    public String getFileUuid(Long fileId) {
        return fileRepository.findById(fileId)
                .map(UploadedFile::getStoredFileName)
                .orElseThrow(() -> new RuntimeException("File not found: " + fileId));
    }

    public EmbeddingStore<TextSegment> getEmbeddingStore() {
        return this.embeddingStore;
    }

    public EmbeddingModel getEmbeddingModel() {
        if (this.embeddingModel == null) {
            System.out.println("Lazily initializing BgeSmallEnQuantizedEmbeddingModel...");
            this.embeddingModel = new BgeSmallEnQuantizedEmbeddingModel();
        }
        return this.embeddingModel;
    }

    public void deleteEmbeddingsByFileId(Long fileId) {
        System.out.println("Purging embeddings for file ID: " + fileId);
        List<EmbeddingMetadata> metadataList = metadataRepository.findByUploadedFileId(fileId);
        List<String> vectorIds = metadataList.stream()
                .map(EmbeddingMetadata::getVectorId)
                .collect(java.util.stream.Collectors.toList());

        if (!vectorIds.isEmpty()) {
            try {
                embeddingStore.removeAll(vectorIds);
                System.out.println("Successfully purged " + vectorIds.size() + " vectors from Pinecone.");
            } catch (Exception e) {
                System.out.println("WARNING: Failed to remove vectors from Pinecone: " + e.getMessage() + ". Continuing with database cleanup.");
            }
        }
        
        metadataRepository.deleteAll(metadataList);
        System.out.println("Successfully removed metadata for file ID: " + fileId + " from database.");
    }
}
