package com.knowledge.assistant.service;

import com.knowledge.assistant.entity.EmbeddingMetadata;
import com.knowledge.assistant.entity.UploadedFile;
import com.knowledge.assistant.repository.EmbeddingMetadataRepository;
import com.knowledge.assistant.repository.UploadedFileRepository;
import dev.langchain4j.data.document.Document;
import dev.langchain4j.data.document.splitter.DocumentSplitters;
import dev.langchain4j.data.embedding.Embedding;
import dev.langchain4j.data.segment.TextSegment;
import dev.langchain4j.model.embedding.AllMiniLmL6V2EmbeddingModel;
import dev.langchain4j.model.embedding.EmbeddingModel;
import dev.langchain4j.store.embedding.EmbeddingStore;
import dev.langchain4j.store.embedding.pinecone.PineconeEmbeddingStore;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
@Slf4j
public class EmbeddingService {

    private final EmbeddingMetadataRepository metadataRepository;
    private final UploadedFileRepository fileRepository;
    private final EmbeddingModel embeddingModel;
    private final EmbeddingStore<TextSegment> embeddingStore;

    public EmbeddingService(
            EmbeddingMetadataRepository metadataRepository,
            UploadedFileRepository fileRepository,
            @Value("${pinecone.api-key}") String pineconeApiKey,
            @Value("${pinecone.environment}") String pineconeEnv,
            @Value("${pinecone.project-id}") String pineconeProjectId,
            @Value("${pinecone.index}") String pineconeIndex
    ) {
        this.metadataRepository = metadataRepository;
        this.fileRepository = fileRepository;
        this.embeddingModel = new AllMiniLmL6V2EmbeddingModel();
        
        this.embeddingStore = PineconeEmbeddingStore.builder()
                .apiKey(pineconeApiKey)
                .environment(pineconeEnv)
                .projectId(pineconeProjectId)
                .index(pineconeIndex)
                .build();
    }

    public void chunkAndEmbedDocument(Document document, UploadedFile uploadedFile) {
        log.info("Starting chunking and embedding for file: {}", uploadedFile.getOriginalFileName());
        
        // Use storedFileName (UUID) for metadata to prevent 'ghost' data if IDs are reused
        document.metadata().add("fileUuid", uploadedFile.getStoredFileName());
        document.metadata().add("userId", uploadedFile.getUploadedBy().getId().toString());
        document.metadata().add("source", uploadedFile.getOriginalFileName());

        var documentSplitter = DocumentSplitters.recursive(500, 50);
        List<TextSegment> segments = documentSplitter.split(document);
        
        log.info("Chunks generated: {}", segments.size());

        for (int i = 0; i < segments.size(); i++) {
            TextSegment segment = segments.get(i);
            dev.langchain4j.data.segment.TextSegment updatedSegment = TextSegment.from(
                segment.text(), 
                segment.metadata().copy().add("chunkIndex", String.valueOf(i))
            );

            Embedding embedding = embeddingModel.embed(updatedSegment.text()).content();
            
            // Capture the ID generated by the store
            String vectorId = embeddingStore.add(embedding, updatedSegment);
            
            EmbeddingMetadata metadata = EmbeddingMetadata.builder()
                    .vectorId(vectorId)
                    .chunkText(updatedSegment.text())
                    .uploadedFile(uploadedFile)
                    .build();
            metadataRepository.save(metadata);
        }
        
        log.info("Successfully embedded {} segments into Pinecone.", segments.size());
    }

    public String getFileUuid(Long fileId) {
        return fileRepository.findById(fileId)
                .map(UploadedFile::getStoredFileName)
                .orElseThrow(() -> new RuntimeException("File not found: " + fileId));
    }

    public EmbeddingStore<TextSegment> getEmbeddingStore() {
        return this.embeddingStore;
    }

    public EmbeddingModel getEmbeddingModel() {
        return this.embeddingModel;
    }

    public void deleteEmbeddingsByFileId(Long fileId) {
        log.info("Purging embeddings for file ID: {}", fileId);
        List<EmbeddingMetadata> metadataList = metadataRepository.findByUploadedFileId(fileId);
        List<String> vectorIds = metadataList.stream()
                .map(EmbeddingMetadata::getVectorId)
                .collect(java.util.stream.Collectors.toList());

        if (!vectorIds.isEmpty()) {
            try {
                embeddingStore.removeAll(vectorIds);
                log.info("Successfully purged {} vectors from Pinecone.", vectorIds.size());
            } catch (Exception e) {
                log.warn("Failed to remove vectors from Pinecone: {}. Continuing with database cleanup.", e.getMessage());
            }
        }
        
        metadataRepository.deleteAll(metadataList);
        log.info("Successfully removed metadata for file ID: {} from database.", fileId);
    }
}
