server:
  port: ${PORT:8080}

  servlet:
    context-path: /

  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

spring:

  application:
    name: ai-knowledge-assistant

  datasource:
    url: jdbc:mysql://localhost:3308/knowledge_assistant?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    database-platform: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: localhost
      port: 6380
      # url: ${REDIS_URL:}

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

jwt:
  secret: myVeryStrongSecretKeyForJwtAuthentication2026SecureKey123456
  expiration: 86400000

groq:
  api-key: ${GROQ_API_KEY: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}
  base-url: https://api.groq.com/openai/v1
  model-name: llama-3.3-70b-versatile

openai:
  api-key: ${OPENAI_API_KEY:demo}

pinecone:
  api-key: ${PINECONE_API_KEY:pcsk_6bbBGg_KMu9qoBaCFXAVqg61TeTB1zgaeYCF4zPDSgzHQuP2U8b4yHZyfCB2cFJKFXzfs4}
  index: ${PINECONE_INDEX:knowledge-assistant}
  environment: aped-4627-b74a
  project-name: tpcv32f